Fix default compress algo
elasticdl/pyrecordio pull request #20
Opened 2018-12-19 11:35 UTC by yuyicg

change the default compression algorithm in writer.py from gzip to snappy.

2018-12-19 12:04 UTC, skydoorkai approved these changes
Compressor(2) 最好用定义个Header.Snappy = 2, Compressor(Header.Snappy)比较可读。

2018-12-19 17:48 UTC, zou000 requested changes

2018-12-19 17:48 UTC, zou000 commented on recordio/recordio/file.py
> +    def __init__(self, file_path, mode, *, max_chunk_size=1024, compressor=Compressor(2)):
可直接用compresser=Compressor.snappy

2018-12-19 17:48 UTC, zou000 commented on recordio/recordio/writer.py
> +    def __init__(self, out_file, max_chunk_size, compressor=Compressor(2)):
same

2018-12-19 17:48 UTC, zou000 commented on recordio/tensorflow_op/cc/recordio_chunk_parser.cc
code更改后需重新build artifacts下面的包

2018-12-20 07:30 UTC, zou000 approved these changes

2018-12-20 07:30 UTC, merged